# Generated by Django 2.0.1 on 2018-01-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCPTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('count', models.IntegerField()),
                ('exclude', models.CharField(max_length=300)),
                ('ip_version', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UDPTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('srv_ip', models.GenericIPAddressField()),
                ('srv_port', models.IntegerField()),
                ('packet_pause', models.FloatField()),
                ('port_start', models.IntegerField()),
                ('port_stop', models.IntegerField()),
            ],
        ),
    ]
