# Generated by Django 2.0.1 on 2018-03-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCPTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('count', models.IntegerField()),
                ('exclude', models.CharField(blank=True, max_length=300)),
                ('ip_version', models.IntegerField()),
                ('packet_pause', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('celery_id', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UDPTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('packet_per_second', models.IntegerField()),
                ('is_start', models.BooleanField(default=False)),
                ('celery_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
