# Generated by Django 2.0.1 on 2018-03-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcptraffic',
            name='packet_pause',
        ),
        migrations.AddField(
            model_name='tcptraffic',
            name='packet_per_second',
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='udptraffic',
            name='celery_id',
            field=models.CharField(blank=True, default=122, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='udptraffic',
            name='packet_per_second',
            field=models.BigIntegerField(),
        ),
    ]
